const arrayButtons = [
    {
      text: { en: '`', ru: 'ё' },
      altText: { en: '~', ru: 'ё' },
      br: false,
      type: 'alternative',
      code: 'Backquote',
    },
    {
      text: { en: '1', ru: '1' },
      altText: { en: '!', ru: '!' },
      br: false,
      type: 'alternative',
      code: 'Digit1',
    },
    {
      text: { en: '2', ru: '2' },
      altText: { en: '@', ru: '"' },
      br: false,
      type: 'alternative',
      code: 'Digit2',
    },
    {
      text: { en: '3', ru: '3' },
      altText: { en: '#', ru: '№' },
      br: false,
      type: 'alternative',
      code: 'Digit3',
    },
    {
      text: { en: '4', ru: '4' },
      altText: { en: '$', ru: ';' },
      br: false,
      type: 'alternative',
      code: 'Digit4',
    },
    {
      text: { en: '5', ru: '5' },
      altText: { en: '%', ru: '%' },
      br: false,
      type: 'alternative',
      code: 'Digit5',
    },
    {
      text: { en: '6', ru: '6' },
      altText: { en: '^', ru: ':' },
      br: false,
      type: 'alternative',
      code: 'Digit6',
    },
    {
      text: { en: '7', ru: '7' },
      altText: { en: '&', ru: '?' },
      br: false,
      type: 'alternative',
      code: 'Digit7',
    },
    {
      text: { en: '8', ru: '8' },
      altText: { en: '*', ru: '*' },
      br: false,
      type: 'alternative',
      code: 'Digit8',
    },
    {
      text: { en: '9', ru: '9' },
      altText: { en: '(', ru: '(' },
      br: false,
      type: 'alternative',
      code: 'Digit9',
    },
    {
      text: { en: '0', ru: '0' },
      altText: { en: ')', ru: ')' },
      br: false,
      type: 'alternative',
      code: 'Digit0',
    },
    {
      text: { en: '-', ru: '-' },
      altText: { en: '_', ru: '_' },
      br: false,
      type: 'alternative',
      code: 'Minus',
    },
    {
      text: { en: '=', ru: '=' },
      altText: { en: '+', ru: '+' },
      br: false,
      type: 'alternative',
      code: 'Equal',
    },
    {
      text: { en: 'Backspace', ru: 'Backspace' },
      altText: { en: 'Backspace', ru: 'Backspace' },
      br: true,
      type: 'functional',
      code: 'Backspace',
    },
    {
      text: { en: 'Tab', ru: 'Tab' },
      altText: { en: 'Tab', ru: 'Tab' },
      br: false,
      type: 'functional',
      code: 'Tab',
    },
    {
      text: { en: 'q', ru: 'й' },
      altText: { en: 'q', ru: 'й' },
      br: false,
      type: 'word',
      code: 'KeyQ',
    },
    {
      text: { en: 'w', ru: 'ц' },
      altText: { en: 'w', ru: 'ц' },
      br: false,
      type: 'word',
      code: 'KeyW',
    },
    {
      text: { en: 'e', ru: 'у' },
      altText: { en: 'e', ru: 'у' },
      br: false,
      type: 'word',
      code: 'KeyE',
    },
    {
      text: { en: 'r', ru: 'к' },
      altText: { en: 'r', ru: 'к' },
      br: false,
      type: 'word',
      code: 'KeyR',
    },
    {
      text: { en: 't', ru: 'е' },
      altText: { en: 't', ru: 'е' },
      br: false,
      type: 'word',
      code: 'KeyT',
    },
    {
      text: { en: 'y', ru: 'н' },
      altText: { en: 'y', ru: 'н' },
      br: false,
      type: 'word',
      code: 'KeyY',
    },
    {
      text: { en: 'u', ru: 'г' },
      altText: { en: 'u', ru: 'г' },
      br: false,
      type: 'word',
      code: 'KeyU',
    },
    {
      text: { en: 'i', ru: 'ш' },
      altText: { en: 'i', ru: 'ш' },
      br: false,
      type: 'word',
      code: 'KeyI',
    },
    {
      text: { en: 'o', ru: 'щ' },
      altText: { en: 'o', ru: 'щ' },
      br: false,
      type: 'word',
      code: 'KeyO',
    },
    {
      text: { en: 'p', ru: 'з' },
      altText: { en: 'p', ru: 'з' },
      br: false,
      type: 'word',
      code: 'KeyP',
    },
    {
      text: { en: '[', ru: 'х' },
      altText: { en: '{', ru: 'х' },
      br: false,
      type: 'alternative',
      code: 'BracketLeft',
    },
    {
      text: { en: ']', ru: 'ъ' },
      altText: { en: '}', ru: 'ъ' },
      br: false,
      type: 'alternative',
      code: 'BracketRight',
    },
    {
      text: { en: '\\', ru: '\\' },
      altText: { en: '|', ru: '/' },
      br: false,
      type: 'alternative',
      code: 'Backslash',
    },
    {
      text: { en: 'DEL', ru: 'DEL' },
      altText: { en: 'DEL', ru: 'DEL' },
      br: true,
      type: 'functional',
      code: 'Delete',
    },
    {
      text: { en: 'Caps Lock', ru: 'Caps Lock' },
      altText: { en: 'Caps Lock', ru: 'Caps Lock' },
      br: false,
      type: 'functional',
      code: 'CapsLock',
    },
    {
      text: { en: 'a', ru: 'ф' },
      altText: { en: 'a', ru: 'ф' },
      br: false,
      type: 'word',
      code: 'KeyA',
    },
    {
      text: { en: 's', ru: 'ы' },
      altText: { en: 's', ru: 'ы' },
      br: false,
      type: 'word',
      code: 'KeyS',
    },
    {
      text: { en: 'd', ru: 'в' },
      altText: { en: 'd', ru: 'в' },
      br: false,
      type: 'word',
      code: 'KeyD',
    },
    {
      text: { en: 'f', ru: 'а' },
      altText: { en: 'f', ru: 'а' },
      br: false,
      type: 'word',
      code: 'KeyF',
    },
    {
      text: { en: 'g', ru: 'п' },
      altText: { en: 'g', ru: 'п' },
      br: false,
      type: 'word',
      code: 'KeyG',
    },
    {
      text: { en: 'h', ru: 'р' },
      altText: { en: 'h', ru: 'р' },
      br: false,
      type: 'word',
      code: 'KeyH',
    },
    {
      text: { en: 'j', ru: 'о' },
      altText: { en: 'j', ru: 'о' },
      br: false,
      type: 'word',
      code: 'KeyJ',
    },
    {
      text: { en: 'k', ru: 'л' },
      altText: { en: 'k', ru: 'л' },
      br: false,
      type: 'word',
      code: 'KeyK',
    },
    {
      text: { en: 'l', ru: 'д' },
      altText: { en: 'l', ru: 'д' },
      br: false,
      type: 'word',
      code: 'KeyL',
    },
    {
      text: { en: ';', ru: 'ж' },
      altText: { en: ':', ru: 'ж' },
      br: false,
      type: 'alternative',
      code: 'Semicolon',
    },
    {
      text: { en: `'`, ru: 'э' },
      altText: { en: '"', ru: 'э' },
      br: false,
      type: 'alternative',
      code: 'Quote',
    },
    {
      text: { en: 'ENTER', ru: 'ENTER' },
      altText: { en: 'ENTER', ru: 'ENTER' },
      br: true,
      type: 'functional',
      code: 'Enter',
    },
    {
      text: { en: 'Shift', ru: 'Shift' },
      altText: { en: 'Shift', ru: 'Shift' },
      br: false,
      type: 'functional',
      code: 'ShiftLeft',
    },
    {
      text: { en: 'z', ru: 'я' },
      altText: { en: 'z', ru: 'я' },
      br: false,
      type: 'word',
      code: 'KeyZ',
    },
    {
      text: { en: 'x', ru: 'ч' },
      altText: { en: 'x', ru: 'ч' },
      br: false,
      type: 'word',
      code: 'KeyX',
    },
    {
      text: { en: 'c', ru: 'с' },
      altText: { en: 'c', ru: 'с' },
      br: false,
      type: 'word',
      code: 'KeyC',
    },
    {
      text: { en: 'v', ru: 'м' },
      altText: { en: 'v', ru: 'м' },
      br: false,
      type: 'word',
      code: 'KeyV',
    },
    {
      text: { en: 'b', ru: 'и' },
      altText: { en: 'b', ru: 'и' },
      br: false,
      type: 'word',
      code: 'KeyB',
    },
    {
      text: { en: 'n', ru: 'т' },
      altText: { en: 'n', ru: 'т' },
      br: false,
      type: 'word',
      code: 'KeyN',
    },
    {
      text: { en: 'm', ru: 'ь' },
      altText: { en: 'm', ru: 'ь' },
      br: false,
      type: 'word',
      code: 'KeyM',
    },
    {
      text: { en: ',', ru: 'б' },
      altText: { en: '<', ru: 'б' },
      br: false,
      type: 'alternative',
      code: 'Comma',
    },
    {
      text: { en: '.', ru: 'ю' },
      altText: { en: '>', ru: 'ю' },
      br: false,
      type: 'alternative',
      code: 'Period',
    },
    {
      text: { en: '/', ru: '.' },
      altText: { en: '?', ru: ',' },
      br: false,
      type: 'alternative',
      code: 'Slash',
    },
    {
      text: { en: '⮝', ru: '⮝' },
      altText: { en: '⮝', ru: '⮝' },
      br: false,
      type: 'functional',
      code: 'ArrowUp',
    },
    {
      text: { en: 'Shift', ru: 'Shift' },
      altText: { en: 'Shift', ru: 'Shift' },
      br: true,
      type: 'functional',
      code: 'ShiftRight',
    },
    {
      text: { en: 'Ctrl', ru: 'Ctrl' },
      altText: { en: 'Ctrl', ru: 'Ctrl' },
      br: false,
      type: 'functional',
      code: 'ControlLeft',
    },
    {
      text: { en: 'Win', ru: 'Win' },
      altText: { en: 'Win', ru: 'Win' },
      br: false,
      type: 'functional',
      code: 'OSLeft',
    },
    {
      text: { en: 'Alt', ru: 'Alt' },
      altText: { en: 'Alt', ru: 'Alt' },
      br: false,
      type: 'functional',
      code: 'AltLeft',
    },
    {
      text: { en: ' ', ru: ' ' },
      altText: { en: ' ', ru: ' ' },
      br: false,
      type: 'word',
      code: 'Space',
    },
    {
      text: { en: 'Alt', ru: 'Alt' },
      altText: { en: 'Alt', ru: 'Alt' },
      br: false,
      type: 'functional',
      code: 'AltRight',
    },
    {
      text: { en: '⮜', ru: '⮜' },
      altText: { en: '⮜', ru: '⮜' },
      br: false,
      type: 'functional',
      code: 'ArrowLeft',
    },
    {
      text: { en: '⮟', ru: '⮟' },
      altText: { en: '⮟', ru: '⮟' },
      br: false,
      type: 'functional',
      code: 'ArrowDown',
    },
    {
      text: { en: '⮞', ru: '⮞' },
      altText: { en: '⮞', ru: '⮞' },
      br: false,
      type: 'functional',
      code: 'ArrowRight',
    },
    {
      text: { en: 'Ctrl', ru: 'Ctrl' },
      altText: { en: 'Ctrl', ru: 'Ctrl' },
      br: true,
      type: 'functional',
      code: 'ControlRight',
    },
  ];
  
  export default arrayButtons;
  
  